services:
  api:
    platform: linux/amd64
    container_name: zpwa-api
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - ./api/logs:/zpwa/logs
    working_dir: "/zpwa"
    command: [ "java",
               "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005",
               "-Djava.security.egd=file:/dev/./urandom",
               "-Xmx512m",
               "-Dspring.profiles.active=zpwa-debug",
               "-jar",
               "api.jar" ]